# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=200)),
                ('dob', models.DateField(verbose_name='date of birth')),
                ('doj', models.DateField(verbose_name='date of joining')),
                ('email_id', models.EmailField(max_length=70)),
                ('department', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unisex/Parody')], max_length=1)),
            ],
        ),
    ]
