# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-15 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_code',
            field=models.IntegerField(default=0),
        ),
    ]
