# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-15 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_info', '0002_employee_employee_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='manager',
            field=models.CharField(default='Select Employee', max_length=1),
            preserve_default=False,
        ),
    ]
