# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-15 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_info', '0006_auto_20170415_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='manager',
            field=models.CharField(max_length=100),
        ),
    ]
