# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=200)),
                ('dob', models.DateField(verbose_name='date published')),
                ('doj', models.DateField(verbose_name='date published')),
                ('emp_image', models.ImageField(upload_to=b'')),
                ('email_id', models.EmailField(max_length=70)),
                ('department', models.CharField(choices=[(1, 'Not relevant'), (2, 'Review'), (3, 'Maybe relevant'), (4, 'Relevant'), (5, 'Leading candidate')], max_length=1)),
            ],
        ),
    ]
