# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unisex/Parody')], max_length=1),
        ),
        migrations.AlterField(
            model_name='employee',
            name='dob',
            field=models.DateField(verbose_name='date of birth'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='doj',
            field=models.DateField(verbose_name='date of joining'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_image',
            field=models.ImageField(upload_to=b'', verbose_name='Employee Image'),
        ),
    ]
